# Generated by Django 3.2.8 on 2021-10-09 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lets_cook_it_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='slug',
        ),
    ]
