# Generated by Django 3.2.8 on 2021-10-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_cook_it_app', '0002_remove_categories_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-created_on']},
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='Status',
            new_name='status',
        ),
        migrations.AddField(
            model_name='recipe',
            name='main_ingredient',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
