# Generated by Django 3.2.8 on 2021-10-09 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lets_cook_it_app', '0003_auto_20211009_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='main_ingredient',
        ),
    ]
