# Generated by Django 3.2.8 on 2021-10-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_cook_it_app', '0004_remove_recipe_main_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.CharField(max_length=2),
        ),
    ]
