# Generated by Django 3.2.8 on 2021-10-15 08:13

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_cook_it_app', '0006_alter_recipe_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
        migrations.AddField(
            model_name='recipe',
            name='image_url',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image_url'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_url',
            field=models.URLField(null=True),
        ),
    ]
