# Generated by Django 3.2.8 on 2021-10-17 00:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lets_cook_it_app', '0010_alter_recipe_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='recipe_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_url',
            field=models.URLField(null=True),
        ),
    ]
