# Generated by Django 3.2.8 on 2021-10-17 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lets_cook_it_app', '0011_auto_20211017_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_url',
            field=models.URLField(null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='lets_cook_it_app.recipe')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
