# Generated by Django 3.2.8 on 2021-10-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_cook_it_app', '0012_auto_20211017_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=1),
        ),
    ]
