# Generated by Django 3.2.8 on 2021-10-23 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lets_cook_it_app', '0013_auto_20211017_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='title',
            new_name='name',
        ),
    ]
